name: Build with Maven

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'adopt'
      - name: Publish package
        run: mvn --batch-mode deploy -DaltDeploymentRepository=snapshot-repo::default::file:./repo
      
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: repo

